# Generated by Django 5.0 on 2023-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('material1', models.CharField(max_length=50)),
                ('material2', models.CharField(blank=True, max_length=50)),
                ('material3', models.CharField(blank=True, max_length=50)),
                ('gold_color', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
