# Generated by Django 5.0 on 2024-08-10 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_parution',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
