# Generated by Django 5.0 on 2024-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_date_of_parution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_of_parution',
        ),
    ]
