# Generated by Django 5.0 on 2024-08-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gold_color',
            field=models.CharField(blank=True, choices=[('jaune', 'Or jaune'), ('rose', 'Or rose'), ('blanc', 'Or blanc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material1',
            field=models.CharField(choices=[('or', 'Or'), ('argent', 'Argent'), ('platine', 'Platine'), ('acier', 'Acier'), ('rubis', 'Rubis'), ('saphire', 'Saphire'), ('emeraude', 'Emeraude'), ('diamant', 'Diamant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material2',
            field=models.CharField(blank=True, choices=[('or', 'Or'), ('argent', 'Argent'), ('platine', 'Platine'), ('acier', 'Acier'), ('rubis', 'Rubis'), ('saphire', 'Saphire'), ('emeraude', 'Emeraude'), ('diamant', 'Diamant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material3',
            field=models.CharField(blank=True, choices=[('or', 'Or'), ('argent', 'Argent'), ('platine', 'Platine'), ('acier', 'Acier'), ('rubis', 'Rubis'), ('saphire', 'Saphire'), ('emeraude', 'Emeraude'), ('diamant', 'Diamant')], max_length=50),
        ),
    ]
