# Generated by Django 5.0 on 2024-08-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_gold_color_alter_product_material1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gold_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material1',
            field=models.CharField(choices=[('Or', 'Or'), ('Argent', 'Argent'), ('Platine', 'Platine'), ('Acier', 'Acier'), ('Rubis', 'Rubis'), ('Saphir', 'Saphir'), ('Emeraude', 'Emeraude'), ('Diamant', 'Diamant'), ('Perles', 'Perles')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
