# Generated by Django 5.0 on 2024-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_category_alter_product_gold_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bracelets', 'Bracelet'), ('colliers', 'Collier'), ('boucles-d-oreilles', "Boucles d'oreilles"), ('bagues', 'Bague')], max_length=50),
        ),
    ]
