# Generated by Django 5.0 on 2024-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gold_color',
            field=models.CharField(blank=True, choices=[('jaune', 'Jaune'), ('blanc', 'Blanc'), ('rose', 'Rose')], max_length=50),
        ),
    ]
